### ISSUE TITLE
GitHub Project Team

### ISSUE THREAD

**Issue by GiuseppeTG** [GiuseppeTG/TVmaze#23]
https://github.com/GiuseppeTG/TVmaze/projects?type=classic

@learnwithalfred @GiuseppeTG

**Comment by dasileker** [comment]
### **Hi @GiuseppeTG,** 

### **Good job so far!**
There are some issues that you still need to work on to go to the next project but you are almost there!

## **Highlights**
- nice job on the kanban cards. 

## Required Changes ♻️
_Check the comments under the review._

- please assign all the cards to to team members, right now you only have 3 cards are assigned. 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by OmarRamoun** [comment]
# 🟢 Project Approved! 🏆

## Hi @dasileker, @GiuseppeTG, and @learnwithalfred  👋

Your project is complete! ✔️ 🏁

Congratulations! 🎉.

Happy 😄 Coding 🖥️! and Have a nice day 🌞.

Cheers and Happy coding!👏👏👏

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@omarramoun](https://img.shields.io/github/followers/omarramoun?label=Ramoun&style=social)](https://github.com/omarramoun)
- This is My **Twitter**: [![@omarramoun](https://img.shields.io/twitter/follow/omarramoun?label=ramoun16&style=social)](https://twitter.com/omarramoun)
- This is My **Slack**: [![Ramoun](https://img.shields.io/badge/slack-@Ramoun-brightgreen)](https://slack.com)
------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
